CREATE TABLE SILVER.D_BLOCOS (
    CO_PAIS TEXT,
    CO_BLOCO TEXT,
    NO_BLOCO TEXT,
    NO_BLOCO_ING TEXT,
    NO_BLOCO_ESP TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_NCM (
    CO_NCM VARCHAR(25),
    CO_UNID TEXT,
    CO_SH6 VARCHAR(25),
    CO_PPE VARCHAR(25),
    CO_PPI VARCHAR(25),
    CO_FAT_AGREG VARCHAR(25),
    CO_CUCI_ITEM VARCHAR(25),
    CO_CGCE_N3 VARCHAR(25),
    CO_SIIT VARCHAR(25),
    CO_ISIC_CLASSE VARCHAR(25),
    CO_EXP_SUBSET VARCHAR(25),
    NO_NCM_POR TEXT,
    NO_NCM_ESP TEXT,
    NO_NCM_ING TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_NCM_ISIC (
    CO_ISIC_CLASSE TEXT,
    NO_ISIC_CLASSE TEXT,
    NO_ISIC_CLASSE_ING TEXT,
    NO_ISIC_CLASSE_ESP TEXT,
    CO_ISIC_GRUPO TEXT,
    NO_ISIC_GRUPO TEXT,
    NO_ISIC_GRUPO_ING TEXT,
    NO_ISIC_GRUPO_ESP TEXT,
    CO_ISIC_DIVISAO TEXT,
    NO_ISIC_DIVISAO TEXT,
    NO_ISIC_DIVISAO_ING TEXT,
    NO_ISIC_DIVISAO_ESP TEXT,
    CO_ISIC_SECAO TEXT,
    NO_ISIC_SECAO TEXT,
    NO_ISIC_SECAO_ING TEXT,
    NO_ISIC_SECAO_ESP TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_NCM_SH (
    CO_SH6 TEXT,
    NO_SH6_POR TEXT,
    NO_SH6_ESP TEXT,
    NO_SH6_ING TEXT,
    CO_SH4 TEXT,
    NO_SH4_POR TEXT,
    NO_SH4_ESP TEXT,
    NO_SH4_ING TEXT,
    CO_SH2 TEXT,
    NO_SH2_POR TEXT,
    NO_SH2_ESP TEXT,
    NO_SH2_ING TEXT,
    CO_NCM_SECROM TEXT,
    NO_SEC_POR TEXT,
    NO_SEC_ESP TEXT,
    NO_SEC_ING TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_PAIS (
    CO_PAIS TEXT,
    CO_PAIS_ISON3 TEXT,
    CO_PAIS_ISOA3 TEXT,
    NO_PAIS TEXT,
    NO_PAIS_ING TEXT,
    NO_PAIS_ESP TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_UF (
    CO_UF TEXT,
    SG_UF TEXT,
    NO_UF TEXT,
    NO_REGIAO TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_UNIDADE (
    CO_UNID TEXT,
    NO_UNID TEXT,
    SG_UNID TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_URF (
    CO_URF TEXT,
    NO_URF TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.D_VIA (
    CO_VIA TEXT,
    NO_VIA TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.F_EXPORTACOES_ESTADOS (
    CO_ANO TEXT,
    CO_MES TEXT,
    CO_NCM TEXT,
    CO_UNID TEXT,
    CO_PAIS TEXT,
    SG_UF_NCM TEXT,
    CO_VIA TEXT,
    CO_URF TEXT,
    QT_ESTAT TEXT,
    KG_LIQUIDO TEXT,
    VL_FOB TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);

CREATE TABLE SILVER.F_IMPORTACOES_ESTADOS (
    CO_ANO TEXT,
    CO_MES TEXT,
    CO_NCM TEXT,
    CO_UNID TEXT,
    CO_PAIS TEXT,
    SG_UF_NCM TEXT,
    CO_VIA TEXT,
    CO_URF TEXT,
    QT_ESTAT TEXT,
    KG_LIQUIDO TEXT,
    VL_FOB TEXT,
    VL_FRETE TEXT,
    VL_SEGURO TEXT,
    DATA_CARGA TIMESTAMP  -- Adicionando a coluna data_carga
);


CREATE TABLE GOLD.FACT_COMERCIO_EXTERIOR (
    CO_ANO TEXT,
    CO_MES TEXT,
    CO_NCM TEXT,
    CO_PAIS TEXT,
    SG_UF_NCM TEXT,
    CO_VIA TEXT,
    CO_URF TEXT,
    KG_LIQUIDO TEXT,
    VL_FOB TEXT,
    DATA_CARGA TIMESTAMP,
    TIPO_MOV TEXT
);
